import { StyleSheet } from 'react-native';
import type { Theme } from '@theme/types';

export const createStyles = (theme: Theme) => StyleSheet.create({
  scrollContent: {
    paddingBottom: 120,
  },
  container: {
    flex: 1,
    padding: theme.spacing[4],
    gap: theme.spacing[4],
  },
  title: {
    marginBottom: theme.spacing[1],
  },
  description: {
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing[4],
  },
  card: {
    padding: theme.spacing[4],
    marginBottom: theme.spacing[3],
  },
  label: {
    color: theme.colors.text.primary,
    marginBottom: theme.spacing[2],
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface.primary,
    borderWidth: 1,
    borderColor: theme.colors.border.primary,
    borderRadius: theme.borderRadius.lg,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[2],
    marginBottom: theme.spacing[2],
  },
  searchIconContainer: {
    marginRight: theme.spacing[2],
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: theme.colors.text.primary,
    fontFamily: theme.fontFamily.regular,
  },
  currentLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2],
    paddingVertical: theme.spacing[1],
  },
  currentLocationText: {
    color: theme.colors.primary.DEFAULT,
  },
  mapCard: {
    padding: 0,
    overflow: 'hidden',
    marginBottom: theme.spacing[3],
  },
  mapContainer: {
    width: '100%',
    height: 300,
    backgroundColor: theme.colors.surface.secondary,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholderText: {
    fontSize: 48,
    color: theme.colors.text.tertiary,
    opacity: 0.3,
    fontFamily: theme.fontFamily.regular,
  },
  mapPin: {
    position: 'absolute',
    top: '45%',
    left: '50%',
    transform: [{ translateX: -15 }, { translateY: -30 }],
    width: 30,
    height: 40,
    alignItems: 'center',
  },
  mapPinDot: {
    width: 16,
    height: 16,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.primary.DEFAULT,
    borderWidth: 3,
    borderColor: theme.colors.text.inverse,
    position: 'absolute',
    bottom: 0,
  },
  mapControls: {
    position: 'absolute',
    bottom: theme.spacing[3],
    right: theme.spacing[3],
    gap: theme.spacing[1],
  },
  zoomButton: {
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.surface.primary,
    borderWidth: 1,
    borderColor: theme.colors.border.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  zoomButtonText: {
    fontSize: 20,
    color: theme.colors.text.primary,
    fontFamily: theme.fontFamily.bold,
  },
  formGroup: {
    marginBottom: theme.spacing[4],
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border.primary,
    borderRadius: theme.borderRadius.lg,
    backgroundColor: theme.colors.surface.primary,
    padding: theme.spacing[3],
    fontSize: 16,
    color: theme.colors.text.primary,
    fontFamily: theme.fontFamily.regular,
  },
  lockedInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border.primary,
    borderRadius: theme.borderRadius.lg,
    backgroundColor: theme.colors.surface.secondary,
    padding: theme.spacing[3],
  },
  lockedInputText: {
    flex: 1,
    fontSize: 16,
    color: theme.colors.text.secondary,
    fontFamily: theme.fontFamily.regular,
  },
  lockIcon: {
    fontSize: 16,
    marginLeft: theme.spacing[2],
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.primary[100],
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing[3],
    gap: theme.spacing[2],
    marginBottom: theme.spacing[2],
  },
  infoIcon: {
    width: 24,
    height: 24,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.primary.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIconText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.text.inverse,
    fontFamily: theme.fontFamily.bold,
  },
  infoText: {
    flex: 1,
    color: theme.colors.text.primary,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.surface.primary,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.primary,
    padding: theme.spacing[4],
    flexDirection: 'row',
    gap: theme.spacing[3],
    paddingBottom: theme.spacing[10],
  },
  backButton: {
    flex: 1,
    paddingVertical: theme.spacing[4],
    borderRadius: theme.borderRadius.lg,
    backgroundColor: theme.colors.surface.primary,
    borderWidth: 1,
    borderColor: theme.colors.primary.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: theme.colors.primary.DEFAULT,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: theme.colors.primary.DEFAULT,
    paddingVertical: theme.spacing[4],
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: theme.spacing[2],
  },
  confirmButtonText: {
    color: theme.colors.text.inverse,
  },
});

