import { StyleSheet } from 'react-native';
import type { Theme } from '@theme/types';
import { fontWeightForPlatform } from '@shared/utils/fontWeightForPlatform';
import {
  getHeadingStyle,
  getBodyStyle,
  getCaptionStyle,
} from '../sharedDashboardStyles';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    contentContainer: {
      paddingBottom: theme.spacing[6],
      backgroundColor: theme.colors.background.secondary,
    },
    creditsBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: theme.spacing[5],
      marginTop: theme.spacing[4],
      paddingVertical: theme.spacing[4],
      paddingHorizontal: theme.spacing[4],
      backgroundColor: theme.colors.surface.secondary,
      borderRadius: theme.borderRadius.card.lg,
    },
    creditsLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing[3],
    },
    creditsIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.colors.primary[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    creditsLabel: {
      ...getCaptionStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.tertiary,
      letterSpacing: 0.5,
    },
    creditsValue: {
      fontSize: theme.typography.heading.h4.fontSize,
      fontFamily: theme.fontFamily.bold,
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.primary,
    },
    addCreditsButtonText: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.inverse,
    },
    section: {
      marginTop: theme.spacing[6],
      paddingHorizontal: theme.spacing[5],
    },
    sectionTitle: {
      ...getHeadingStyle(theme, 'h5'),
      color: theme.colors.text.primary,
      marginBottom: theme.spacing[3],
    },
    quickActionsRow: {
      flexDirection: 'row',
      gap: theme.spacing[3],
      marginBottom: theme.spacing[2],
    },
    quickActionCard: {
      flex: 1,
      borderRadius: theme.borderRadius.card.lg,
      padding: theme.spacing[5],
      minHeight: 120,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    quickActionCardWrapper: {
      backgroundColor: 'transparent',
    },
    quickActionGradientCanvas: {
      ...StyleSheet.absoluteFillObject,
    },
    quickActionContent: {
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    quickActionIconBg: {
      position: 'absolute',
      right: theme.spacing[1],
      top: -theme.spacing[2],
      opacity: 0.1,
    },
    quickActionIcon: {
      marginBottom: theme.spacing[2],
    },
    quickActionLabel: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.inverse,
      textAlign: 'center',
    },
    quickActionSubtext: {
      marginTop: theme.spacing[1],
      ...getCaptionStyle(theme, 'medium'),
      color: theme.colors.text.inverse,
      textAlign: 'center',
      opacity: 0.9,
    },
    snapshotCardsRow: {
      flexDirection: 'row',
      gap: theme.spacing[3],
    },
    snapshotCard: {
      flex: 1,
      minHeight: 100,
      backgroundColor: theme.colors.surface.primary,
      borderRadius: theme.borderRadius.card.lg,
      padding: theme.spacing[4],
      borderWidth: 1,
      borderColor: theme.colors.border.primary,
      justifyContent: 'space-between',
    },
    snapshotCardLabel: {
      ...getCaptionStyle(theme, 'medium'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.secondary,
      marginBottom: theme.spacing[2],
    },
    snapshotCardValue: {
      fontSize: theme.typography.heading.h4.fontSize,
      fontFamily: theme.fontFamily.bold,
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.primary,
      marginBottom: theme.spacing[2],
    },
    snapshotCardSub: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing[1],
      minHeight: 20,
    },
    snapshotCardSubText: {
      ...getCaptionStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.tertiary,
    },
    activeSessionsSection: {
      marginTop: theme.spacing[6],
      paddingHorizontal: theme.spacing[5],
    },
    emptySessionsCard: {
      backgroundColor: theme.colors.surface.primary,
      borderRadius: theme.borderRadius.card.lg,
      padding: theme.spacing[6],
      alignItems: 'center',
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: theme.colors.border.primary,
    },
    emptySessionsIconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.colors.primary[50],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: theme.spacing[3],
    },
    emptySessionsTitle: {
      ...getHeadingStyle(theme, 'h6'),
      color: theme.colors.text.primary,
      marginBottom: theme.spacing[1],
    },
    emptySessionsDesc: {
      ...getBodyStyle(theme, 'small'),
      color: theme.colors.text.secondary,
      textAlign: 'center',
      marginBottom: theme.spacing[4],
    },
    viewAllSessionsButtonText: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.inverse,
    },
    sessionCard: {
      backgroundColor: theme.colors.surface.primary,
      borderRadius: theme.borderRadius.card.lg,
      padding: theme.spacing[4],
      marginBottom: theme.spacing[3],
      borderWidth: 1,
      borderColor: theme.colors.border.primary,
    },
    sessionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing[3],
    },
    sessionStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing[1],
    },
    sessionStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    sessionStatusText: {
      ...getCaptionStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.text.primary,
      letterSpacing: 0.3,
    },
    sessionTimeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.primary[50],
      paddingHorizontal: theme.spacing[2],
      paddingVertical: theme.spacing[1],
      borderRadius: theme.borderRadius.input.md,
      gap: theme.spacing[1],
    },
    sessionTimeText: {
      fontSize: 12,
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.primary.DEFAULT,
    },
    sessionContent: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: theme.spacing[3],
    },
    sessionAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.primary[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing[3],
    },
    sessionAvatarText: {
      ...getBodyStyle(theme, 'medium'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.primary.DEFAULT,
    },
    sessionInfo: {
      flex: 1,
    },
    sessionCompany: {
      ...getBodyStyle(theme, 'medium'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.primary,
      marginBottom: 2,
    },
    sessionDescription: {
      ...getBodyStyle(theme, 'small'),
      color: theme.colors.text.secondary,
    },
    actionButton: {
      backgroundColor: theme.colors.warning.DEFAULT,
      paddingHorizontal: theme.spacing[3],
      paddingVertical: theme.spacing[2],
      borderRadius: theme.borderRadius.button.sm,
    },
    actionButtonText: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.inverse,
    },
    chatButton: {
      width: 40,
      height: 40,
      borderRadius: theme.borderRadius.input.md,
      backgroundColor: theme.colors.surface.tertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionProgress: {
      marginBottom: theme.spacing[2],
    },
    progressMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing[2],
    },
    progressMetaLabel: {
      ...getCaptionStyle(theme, 'medium'),
      color: theme.colors.text.primary,
    },
    progressMetaValue: {
      ...getCaptionStyle(theme, 'medium'),
      fontWeight: fontWeightForPlatform('700'),
      color: theme.colors.primary.DEFAULT,
    },
    progressBar: {
      height: 4,
      backgroundColor: theme.colors.border.primary,
      borderRadius: 2,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: theme.colors.primary.DEFAULT,
      borderRadius: 2,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing[3],
    },
    viewAllText: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.primary.DEFAULT,
    },
    viewAllButton: {
      backgroundColor: theme.colors.primary.DEFAULT,
      color: theme.colors.primary.DEFAULT,
      borderRadius: theme.borderRadius.button.sm,
    },
    viewAllButtonText: {
      ...getBodyStyle(theme, 'small'),
      fontWeight: fontWeightForPlatform('600'),
      color: theme.colors.text.inverse,
    },
  });
