import { StyleSheet } from 'react-native';
import type { Theme } from '@theme/types';

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: theme.spacing[5],
    paddingBottom: theme.spacing[5],
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.background.primary,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  editButton: {
    paddingVertical: theme.spacing[1],
  },
  editButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.primary.DEFAULT,
  },
  scrollContent: {
    paddingBottom: theme.spacing[5],
  },
  profileCardContainer: {
    marginHorizontal: theme.spacing[5],
    marginTop: theme.spacing[5],
    alignItems: 'center',
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: theme.spacing[4],
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: theme.colors.primary[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.colors.primary.light,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: theme.colors.background.primary,
  },
  profileImageIcon: {
    fontSize: 40,
    color: theme.colors.primary.dark,
    marginBottom: theme.spacing[1],
  },
  profileImageText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.primary.dark,
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.primary.DEFAULT,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: theme.colors.background.primary,
  },
  verifiedCheckmark: {
    color: theme.colors.text.inverse,
    fontSize: 16,
    fontWeight: 'bold',
  },
  companyName: {
    fontSize: 22,
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginBottom: theme.spacing[1],
    textAlign: 'center',
  },
  supplierType: {
    fontSize: 14,
    fontWeight: '400',
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing[3],
  },
  activeButton: {
    backgroundColor: theme.colors.primary.DEFAULT,
    paddingHorizontal: theme.spacing[4],
    paddingVertical: 6,
    borderRadius: theme.borderRadius.lg,
  },
  activeButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 12,
    fontWeight: '600',
  },
  section: {
    marginTop: theme.spacing[6],
    paddingHorizontal: theme.spacing[5],
  },
  contactItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing[3],
    gap: theme.spacing[3],
  },
  contactIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing[3],
  },
  contactIconText: {
    fontSize: 18,
  },
  contactInfo: {
    flex: 1,
  },
  contactLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: theme.colors.text.tertiary,
    marginBottom: theme.spacing[1],
  },
  contactValue: {
    fontSize: 16,
    fontWeight: '500',
    color: theme.colors.text.primary,
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surface.primary,
    padding: theme.spacing[4],
    borderRadius: theme.borderRadius.lg,
    marginBottom: theme.spacing[3],
    shadowColor: theme.colors.text.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  settingsItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  settingsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing[3],
  },
  settingsIconText: {
    fontSize: 18,
  },
  settingsLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: theme.colors.text.primary,
  },
  settingsArrow: {
    fontSize: 18,
    color: theme.colors.text.tertiary,
  },
  logoutButton: {
    backgroundColor: theme.colors.error.DEFAULT,
    marginHorizontal: theme.spacing[5],
    marginTop: theme.spacing[6],
    paddingVertical: theme.spacing[4],
    borderRadius: theme.borderRadius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.text.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  logoutButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: theme.spacing[2],
  },
  logoutIcon: {
    fontSize: 18,
    color: theme.colors.text.inverse,
  },
  versionText: {
    textAlign: 'center',
    marginTop: theme.spacing[6],
    marginBottom: theme.spacing[5],
    fontSize: 12,
    fontWeight: '400',
    color: theme.colors.text.tertiary,
  },
  // Profile Completion Styles
  completionCard: {
    marginHorizontal: theme.spacing[5],
    marginTop: theme.spacing[5],
    backgroundColor: theme.colors.warning.light,
    borderWidth: 1,
    borderColor: theme.colors.warning.DEFAULT,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing[4],
  },
  completionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing[3],
  },
  completionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.warning.DEFAULT,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing[3],
  },
  completionIcon: {
    fontSize: 20,
  },
  completionTextContainer: {
    flex: 1,
  },
  completionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginBottom: 2,
  },
  completionSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: theme.colors.text.secondary,
  },
  incompleteFieldsList: {
    marginBottom: theme.spacing[3],
    paddingLeft: theme.spacing[2],
  },
  incompleteFieldItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing[1],
  },
  incompleteFieldDot: {
    fontSize: 12,
    color: theme.colors.warning.dark,
    marginRight: theme.spacing[2],
    fontWeight: 'bold',
  },
  incompleteFieldText: {
    fontSize: 14,
    fontWeight: '400',
    color: theme.colors.text.primary,
  },
  completeProfileButton: {
    backgroundColor: theme.colors.primary.DEFAULT,
    paddingVertical: theme.spacing[3],
    paddingHorizontal: theme.spacing[4],
    borderRadius: theme.borderRadius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  completeProfileButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 14,
    fontWeight: '600',
    marginRight: theme.spacing[2],
  },
  completeProfileArrow: {
    color: theme.colors.text.inverse,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Loading and Error States
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing[5],
  },
  loadingText: {
    marginTop: theme.spacing[3],
    fontSize: 16,
    color: theme.colors.text.secondary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing[5],
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: theme.spacing[4],
  },
  errorText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing[5],
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: theme.colors.primary.DEFAULT,
    paddingHorizontal: theme.spacing[6],
    paddingVertical: theme.spacing[3],
    borderRadius: theme.borderRadius.md,
  },
  retryButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 16,
    fontWeight: '600',
  },
  // Status Container
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2],
    marginTop: theme.spacing[2],
  },
  verifiedTag: {
    backgroundColor: theme.colors.success.light,
    paddingHorizontal: theme.spacing[3],
    paddingVertical: theme.spacing[1],
    borderRadius: theme.borderRadius.lg,
  },
  verifiedTagText: {
    color: theme.colors.success.dark,
    fontSize: 11,
    fontWeight: '600',
  },
  // Roles Section
  rolesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing[3],
  },
  roleBadge: {
    backgroundColor: theme.colors.primary.light,
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[3],
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.primary[300],
    minWidth: 140,
    alignItems: 'flex-start',
  },
  roleBadgeLabel: {
    marginBottom: theme.spacing[1],
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  roleBadgeValue: {
    textTransform: 'capitalize',
  },
  roleBadgeActive: {
    backgroundColor: theme.colors.primary.DEFAULT,
    borderColor: theme.colors.primary.dark,
  },
  roleBadgeDisabled: {
    opacity: 0.6,
  },
  roleBadgeContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  roleBadgeLeft: {
    flex: 1,
  },
  activeRoleIndicator: {
    backgroundColor: theme.colors.success.DEFAULT,
    paddingHorizontal: theme.spacing[2],
    paddingVertical: 4,
    borderRadius: theme.borderRadius.md,
    marginLeft: theme.spacing[2],
  },
  activeRoleText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.text.inverse,
    textTransform: 'uppercase',
  },
  switchRoleText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.primary.DEFAULT,
    marginLeft: theme.spacing[2],
  },
  roleSwitchHint: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing[2],
    fontStyle: 'italic',
    lineHeight: 16,
  },
  // Contact Info Enhancements
  contactLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing[1],
  },
  verifiedIndicator: {
    backgroundColor: theme.colors.success.light,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.md,
  },
  verifiedIndicatorText: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.success.dark,
  },
  // Info Icon Container
  infoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoIconText: {
    fontSize: 20,
  },
  // Verification Status
  verificationCard: {
    marginBottom: theme.spacing[3],
    padding: theme.spacing[4],
  },
  verificationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing[1],
  },
  verificationLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.text.primary,
    flex: 1,
  },
  verificationStatus: {
    paddingHorizontal: theme.spacing[3],
    paddingVertical: 6,
    borderRadius: theme.borderRadius.lg,
  },
  verificationStatusVerified: {
    backgroundColor: theme.colors.success.light,
  },
  verificationStatusPending: {
    backgroundColor: theme.colors.warning.light,
  },
  verificationStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  verificationDate: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing[1],
    fontStyle: 'italic',
  },
});
