/** STEP 1: Choose product category (converter upload flow) */
export const RTD_CATEGORY_OPTIONS: string[] = [
  'Corrugated Boxes (all ply variants)',
  'Rigid Boxes (all structures)',
  'Rigid Box',
  'Folding Cartons',
  'Mono Cartons',
  'Mono Carton',
  'Mailer Box',
  'Brown kraft mailers',
  'White mailers',
  'Paper Bag',
  'Paper carry bags',
  'Kraft bags',
  'Box sleeves',
  'Belly bands',
  'Apparel boxes',
  'Display Units',
  'Shelf Ready Packaging',
  'Dump Bins',
  'Counter Displays',
  'POS Materials',
  'Gift Boxes',
  'Corporate Gifting Boxes',
  'Promotional Kits',
  'Subscription Boxes',
  'Festive Hampers',
  'Luxury Presentation Boxes',
  'Cake Boxes',
  'Pizza Boxes',
  'Burger Boxes',
  'Meal Boxes',
  'Food Trays',
  'Paper Cups',
  'Paper Bowls',
  'Paper Plates',
  'Paper Lids',
  'Food Wrap Sheets',
  'Books',
  'Notebooks',
  'Notebook',
  'Diaries',
  'Diaries (standard sizes)',
  'Diary',
  'Planners',
  'Calendars',
  'Corporate folders',
  'Registers',
  'Catalogues',
  'Brochures',
  'Flyers',
  'Manuals',
  'Annual Reports',
  'Certificates',
  'Envelopes',
  'Envelope',
  'Files & Folders',
  'Folder',
  'Sleeves',
  'Inserts',
  'Insert / Flyer',
  'Leaflets',
  'Thank-you cards',
  'Instruction cards',
  'Warranty Cards',
  'Product Labels',
  'Barcode Labels',
  'Security Labels',
  'Garment Tags',
  'Hang Tags',
  'RFID Tags',
  'Paper Tubes',
  'Paper Cores',
  'Honeycomb Panels',
  'Edge Protectors',
  'Paper Pallets',
  'Cushioning Sheets',
];

export const SIZE_UNIT_OPTIONS: { label: string; value: 'inches' | 'cm' | 'mm' }[] = [
  { label: 'Inches', value: 'inches' },
  { label: 'CM', value: 'cm' },
  { label: 'MM', value: 'mm' },
];

export const THICKNESS_UNIT_OPTIONS: {
  label: string;
  value: 'GSM' | 'MM' | 'OUNCE' | 'BF' | 'MICRON';
}[] = [
  { label: 'GSM', value: 'GSM' },
  { label: 'MM', value: 'MM' },
  { label: 'OUNCE', value: 'OUNCE' },
  { label: 'BF', value: 'BF' },
  { label: 'MICRON', value: 'MICRON' },
];

export const BRANDING_METHOD_OPTIONS = [
  'Screen printing',
  'Offset printing',
  'Foil stamping',
  'UV',
  'Emboss',
  'Sticker',
  'Sleeves',
];
