import { StyleSheet } from 'react-native';
import type { Theme } from '@theme/types';

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing[4],
  },
  logo: {
    fontSize: 48,
    fontWeight: '900',
    color: theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: theme.spacing[6],
    fontFamily: theme.fontFamily.bold,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: theme.colors.text.primary,
    marginBottom: theme.spacing[2],
    textAlign: 'center',
    fontFamily: theme.fontFamily.bold,
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing[8],
    textAlign: 'center',
    lineHeight: 20,
    fontFamily: theme.fontFamily.regular,
    paddingHorizontal: theme.spacing[2],
  },
  formContainer: {
    width: '100%',
    maxWidth: 400,
    marginBottom: theme.spacing[8],
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: theme.spacing[2],
    fontFamily: theme.fontFamily.medium,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border.primary,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing[4],
    fontSize: 16,
    backgroundColor: theme.colors.surface.primary,
    marginBottom: theme.spacing[6],
    color: theme.colors.text.primary,
    fontFamily: theme.fontFamily.regular,
  },
  button: {
    backgroundColor: theme.colors.primary.DEFAULT,
    paddingVertical: theme.spacing[4],
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: theme.spacing[2],
  },
  buttonDisabled: {
    backgroundColor: theme.colors.text.disabled,
    opacity: 0.6,
  },
  buttonText: {
    color: theme.colors.text.inverse,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: theme.fontFamily.medium,
  },
  footer: {
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
  },
  footerText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    marginBottom: theme.spacing[6],
    lineHeight: 18,
    fontFamily: theme.fontFamily.regular,
    paddingHorizontal: theme.spacing[2],
  },
  link: {
    color: theme.colors.primary.DEFAULT,
    fontWeight: '600',
    fontFamily: theme.fontFamily.medium,
  },
  securityBadges: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.spacing[6],
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[1],
  },
  badgeDivider: {
    width: 1,
    height: 16,
    backgroundColor: theme.colors.border.primary,
    marginHorizontal: theme.spacing[3],
  },
  badgeIcon: {
    fontSize: 16,
  },
  badgeText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontFamily: theme.fontFamily.regular,
  },
  helpLink: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    fontWeight: '400',
    fontFamily: theme.fontFamily.regular,
  },
});
